"""ISO/IEC 27001:2022 Annex A controls used by the assessment.

Only 15 selected controls are included. Titles follow the official
2022 edition Annex A naming. The evidence strings are short, original
descriptions of the type of evidence an organisation could keep.

The status / likelihood / impact values are SIMULATED starting data so
the app is not empty on first run. They are editable in the UI.
"""

FRAMEWORK = "ISO/IEC 27001:2022"

IMPLEMENTATION_STATUSES = [
    "Not Assessed",
    "Implemented",
    "Partially Implemented",
    "Not Implemented",
    "Not Applicable",
]

CONTROLS = [
    {
        "id": "A.5.1",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Policies for information security",
        "evidence": "Approved information security policy with review and approval records.",
        "status": "Implemented",
        "likelihood": 2,
        "impact": 2,
    },
    {
        "id": "A.5.7",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Threat intelligence",
        "evidence": "Subscriptions to threat feeds and a documented advisory review process.",
        "status": "Partially Implemented",
        "likelihood": 3,
        "impact": 3,
    },
    {
        "id": "A.5.15",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Access control",
        "evidence": "Access control policy with least-privilege rules applied to systems.",
        "status": "Implemented",
        "likelihood": 2,
        "impact": 4,
    },
    {
        "id": "A.5.16",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Identity management",
        "evidence": "Identity lifecycle process covering creation, change, and removal of accounts.",
        "status": "Not Assessed",
        "likelihood": 3,
        "impact": 3,
    },
    {
        "id": "A.5.18",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Access rights",
        "evidence": "Access request approvals and completed periodic access reviews.",
        "status": "Partially Implemented",
        "likelihood": 4,
        "impact": 4,
    },
    {
        "id": "A.5.23",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Information security for use of cloud services",
        "evidence": "Cloud service agreements and a list of approved cloud providers.",
        "status": "Not Assessed",
        "likelihood": 3,
        "impact": 4,
    },
    {
        "id": "A.5.24",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Information security incident management planning and preparation",
        "evidence": "Incident response plan, roles, and records of practice or test exercises.",
        "status": "Implemented",
        "likelihood": 2,
        "impact": 3,
    },
    {
        "id": "A.5.28",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Collection of evidence",
        "evidence": "Preservation procedure for logs and artefacts used in incident handling.",
        "status": "Not Assessed",
        "likelihood": 3,
        "impact": 3,
    },
    {
        "id": "A.5.31",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Legal, statutory, regulatory and contractual requirements",
        "evidence": "Register of applicable laws and contracts with owners and review dates.",
        "status": "Partially Implemented",
        "likelihood": 4,
        "impact": 5,
    },
    {
        "id": "A.5.34",
        "framework": FRAMEWORK,
        "category": "Organizational",
        "name": "Privacy and protection of PII",
        "evidence": "Privacy notices, consent records, and data processing agreements.",
        "status": "Not Implemented",
        "likelihood": 4,
        "impact": 5,
    },
    {
        "id": "A.8.2",
        "framework": FRAMEWORK,
        "category": "Technological",
        "name": "Privileged access rights",
        "evidence": "Privileged account inventory, approval records, and review of usage.",
        "status": "Partially Implemented",
        "likelihood": 4,
        "impact": 5,
    },
    {
        "id": "A.8.5",
        "framework": FRAMEWORK,
        "category": "Technological",
        "name": "Secure authentication",
        "evidence": "MFA configuration and an authentication policy for all user access.",
        "status": "Implemented",
        "likelihood": 2,
        "impact": 4,
    },
    {
        "id": "A.8.8",
        "framework": FRAMEWORK,
        "category": "Technological",
        "name": "Management of technical vulnerabilities",
        "evidence": "Vulnerability scan reports, patch records, and remediation tracking.",
        "status": "Partially Implemented",
        "likelihood": 4,
        "impact": 4,
    },
    {
        "id": "A.8.15",
        "framework": FRAMEWORK,
        "category": "Technological",
        "name": "Logging",
        "evidence": "Log generation and retention configuration with a sample audit log.",
        "status": "Implemented",
        "likelihood": 2,
        "impact": 3,
    },
    {
        "id": "A.8.16",
        "framework": FRAMEWORK,
        "category": "Technological",
        "name": "Monitoring activities",
        "evidence": "Monitoring or alerting rules and records of reviewed alerts.",
        "status": "Not Implemented",
        "likelihood": 4,
        "impact": 4,
    },
]